export const ArtData = [
  {
    id: 1,
    painting: require('../assets/pictures/Artwork.png'),
    author: 'George Dillan',
    title: 'Forest silence',
    photo: require('../assets/pictures/Artist1.png'),
    removed: false,
  },
  {
    id: 2,
    painting: require('../assets/pictures/Artwork 2.png'),
    author: 'Peggy Wood',
    title: 'Still life V',
    photo: require('../assets/pictures/Artist2.png'),
    removed: false,
  },
  {
    id: 3,
    painting: require('../assets/pictures/Artwork 3.png'),
    author: 'Alice Gordan',
    title: 'Surrounded',
    photo: require('../assets/pictures/Artist3.png'),
    removed: false,
  },
  {
    id: 4,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 5,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 6,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 7,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 8,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 9,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 10,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 11,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 12,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 13,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 14,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 15,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 16,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 17,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 18,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 19,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 20,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 21,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 22,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 23,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 24,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 25,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 26,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 27,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 28,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 29,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 30,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 31,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 32,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 33,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 34,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
  {
    id: 35,
    painting: require('../assets/pictures/Artwork 4.png'),
    author: 'Timothy Taylor',
    title: 'Mountain landscape',
    photo: require('../assets/pictures/Artist4.png'),
    removed: false,
  },
];
